export interface CoupleNames {
  person1: string;
  person2: string;
}

export interface StoryAnswers {
  names: CoupleNames;
  meeting: string;
  attraction: string;
  memorable: string;
  challenges: string;
  future: string;
  genres: string[];
}

export interface StoryAnalysis {
  id: string;
  summary: string;
  mood: string;
  themes: string[];
  songs: SongPrompt[]; // Array with exactly 1 song
}

export interface SongPrompt {
  id: string;
  title: string;
  description: string;
  mood: string;
  genre: string;
  lyrics: string; // Now required - generated by OpenAI
  prompt: string;
}

export interface GeneratedSong {
  id: string;
  title: string;
  audioUrl: string;
  duration?: number;
  status: 'generating' | 'completed' | 'failed';
  version?: 'A' | 'B'; // For handling 2 songs returned by Suno API
  lyrics?: string; // Song lyrics/prompt text
}

export interface SongGenerationState {
  promptId: string;
  title: string;
  status: 'not_generated' | 'generating' | 'completed' | 'failed';
  songs: GeneratedSong[];
  taskId?: string; // Suno task ID for ongoing generation
  startedAt?: number; // Timestamp when generation started
  error?: string;
}

export interface TaskStartResponse {
  taskId: string;
  status: 'generating';
}

export interface TaskPollResponse {
  taskId: string;
  status: 'generating' | 'completed' | 'failed';
  songs?: GeneratedSong[];
  error?: string;
}

export interface AlbumCover {
  id: string;
  imageUrl: string;
  prompt: string;
  status: 'generating' | 'completed' | 'failed';
}

export interface Album {
  id: string;
  title: string;
  artist: string;
  story: string;
  storyAnswers?: StoryAnswers; // New structured story data
  analysis: StoryAnalysis; // Contains 1 song
  songs: GeneratedSong[]; // Generated song(s) - typically 1-2 versions
  cover?: AlbumCover; // COMMENTED OUT: Made optional - cover generation disabled
  createdAt: Date;
}

export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
}